### PR TITLE
cut new version 0.1.2-dev to bump hdk 0.2.8 hdi 0.3.8 

### PR DESCRIPTION
**Pull request by dauphin3**
upgrade to Holochain recommend release version 0.2.8

### CODE REVIEW

**Comment by harlantwood** [comment]
Thanks @dauphin3 !

Looks great except the package.json, did you mean to commit that?  We use bin/run for scripts…

**Comment by dauphin3** [comment]
@harlantwood ah oops, no.  amended.

**Review by harlantwood — APPROVED** [review]
Looks good, thanks for the PR!

**Comment by harlantwood** [comment]
✨

**Pull request merged**
